# Generated by Django 2.0.2 on 2019-07-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operations', '0001_initial'),
        ('Exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.CourseList', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.Question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.CourseList', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.Paper', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='useranswerlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='papercache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='create_paper',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exams.CourseList', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='create_paper',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.PaperList', verbose_name='试卷名称'),
        ),
    ]
