# Generated by Django 2.0.2 on 2019-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_auto_20190812_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlist',
            name='random_paper',
            field=models.BooleanField(default=True, verbose_name='随机卷'),
        ),
    ]
